version: "3" # optional since v1.27.0
services:
  db:
    container_name: mongo-server
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/docker-volumes/data/db:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
    networks:
      - mongo_network
    depends_on:
      - db

  remind-me-server:
    container_name: remind-me-server
    command: npm run dev:start
    volumes:
      - ./src:/usr/app/src
      - ./nodemon.json:/usr/app/nodemon.json
    build:
      context: .
      dockerfile: Dockerfile
    image: remind-me-server:dev
    expose:
      - 4000
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      - DB_NAME="${DB_NAME}"
      - CONNECTION_STRING="mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017"
    depends_on:
      - db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
