version: "3" # optional since v1.27.0
services:
  remind-me-server:
    container_name: remind-me-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: remind-me-server:dev
    ports:
      - 4000:4000
    environment:
      - CONNECTION_STRING=mongodb://root:example@mongo:27017
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
