version: "3" # optional since v1.27.0
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  remind-me-server:
    container_name: remind-me-server
    command: npm start
    build:
      context: .
      dockerfile: Dockerfile
    image: remind-me-server:prod
    expose:
      - 4000
    ports:
      - 4000:4000
    environment:
      - CONNECTION_STRING=mongodb://root:example@mongo:27017
    links:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
